<?php echo var_dump($block->isEnabled());?>
<h2>Welcome </h2>
<p><?php echo $block->getEmail();?></p>


<p><?php echo $block->getFrequency();?></p>

<p><?php echo $block->getTime();?></p>

<table>
	<tr>
		<td>ID</td>
		<td>Status</td>
	</tr>
<?php foreach($block->getOrderCollection() as $item){ ?>
	<tr>
		<td><?php echo $item->getId();?></td>
		<td><?php echo $item->getStatus();?></td>
		<td><?php echo $item->getCustomer_firstname();?></td>
	</tr>
<?php }?>
</table>



